name: Build and Publish Action

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    concurrency: build-and-publish

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "20"

      - name: Install dependencies
        run: npm install

      - name: Build action with ncc
        run: npm run build

      - name: Publish to GitHub
        uses: actions/upload-artifact@v4
        with:
          name: action
          path: dist
