name: "Validate Action"
on:
  pull_request:
  push:
    branches:
      - main
jobs:
  validate:
    name: Test the github action
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - uses: actions/setup-node@v4
        with:
          node-version-file: .node-version

      - name: Install dependencies
        run: npm install

      - name: Run JSON File Action
        uses: ./ # Assuming the action is in the root directory
        with:
          json-file-path: "__tests__/test.json"
          example-app: "sample-app-3"
          build-script: "__tests__/build_script.sh"
